server:
  port: 8097

spring:

  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2              환경변수로 설정할때 아래.
    username: x # 3  ${mail.username}
    password: x # 4 ${mail.password}
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springnew
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
#
#  profiles:
#    include: oauth2
